name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # os: [windows-latest, ubuntu-latest, macos-latest]
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
        with:
          cache-workspace-crates: "true"
      - name: Build
        run: cargo build -vv
      # - name: Run tests
      #   run: cargo test --verbose -- --no-capture
      # - name: Lint code
      #   if: matrix.os == 'macos-latest'
      #   run: cargo clippy
      # - name: Check code style
      #   if: matrix.os == 'macos-latest'
      #   run: cargo fmt --check
      # - name: Spell check
      #   if: matrix.os == 'macos-latest'
      #   uses: crate-ci/typos@v1
      # - name: Test f64 build
      #   run: cargo test --verbose --features use_f64 -- --no-capture
